 Используем базовый образ с CUDA
FROM nvidia/cuda:12.4.1-devel-ubuntu22.04

# Установка основных пакетов
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    python3.10 \
    python3-pip \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Установка PyTorch, torchvision и torchaudio с поддержкой CUDA
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

# Установите переменную окружения CUDA_HOME
ENV CUDA_HOME=/usr/local/cuda

# Установка protobuf и необходимых пакетов
RUN pip install protobuf wandb flask langchain einops transformers accelerate bitsandbytes tensorflow
# Скопируйте вашу модель и другие необходимые файлы в контейнер
# Здесь предполагается, что у вас есть скрипт flask_api.py в директории /app
WORKDIR /app

# Опционально: задайте версию Python по умолчанию на 3.10
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1

# Удаление ненужных пакетов и очистка
RUN apt autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

# Определите порт, который будет использовать Flask
EXPOSE 8080

# По умолчанию запустим команду bash
CMD ["/bin/bash"]

# # По умолчанию запустим команду для запуска Flask API
# CMD ["python3", "flask_api.py"]
